default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: task_development

test:
  <<: *default
  database: task_test

production:
  <<: *default
  database: task_production
  username: admin
  password: <%= ENV['TASK_DATABASE_PASSWORD'] %>
